### ISSUE TITLE
Trap IOError in sound setup

### ISSUE THREAD

**Issue by druck13** [skymandr/brandmateriel#1]
To get it to run on my Linux machine, I had to change line 39 of brandmaterial/src/menu.py to:-
`except (pygame.error, IOError):`

Nice implementation, brings back lots of memories!

**Comment by skymandr** [comment]
Thanks, I've fixed it. Sounds was something I never got around to doing, but I've left a few skeletons of the attempt in the code.

Since you seem to know the original, I can reveal that there is a hidden toggle under the Options menu, which will give you a slightly more authentic experience.
